/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package diffie.hellman;

import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.security.AlgorithmParameterGenerator;
import java.security.AlgorithmParameters;
import java.security.Key;
import java.security.KeyFactory;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.PublicKey;
import java.security.spec.X509EncodedKeySpec;
import javax.crypto.Cipher;
import javax.crypto.KeyAgreement;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

/**
 *
 * @author DzurTrwgn
 */
public class Alice extends javax.swing.JFrame {

    /**
     * Creates new form Alice
     */
    public Alice() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtKeyAlice = new javax.swing.JTextField();
        txtKeyBoB = new javax.swing.JTextField();
        txtKeyKAB = new javax.swing.JTextField();
        txtEncyptKAB = new javax.swing.JTextField();
        btnKeyAlice = new javax.swing.JButton();
        btnDisplayKeyBoB = new javax.swing.JButton();
        btnKeyAB = new javax.swing.JButton();
        btnEncyptKAB = new javax.swing.JButton();
        btnEncOrDec = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Alice");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Key Alice:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Key BoB:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Key KAB:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Encypt KAB:");

        txtKeyAlice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKeyAliceActionPerformed(evt);
            }
        });

        btnKeyAlice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKeyAlice.setText("Create Key A");
        btnKeyAlice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeyAliceActionPerformed(evt);
            }
        });

        btnDisplayKeyBoB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDisplayKeyBoB.setText("Display KB");
        btnDisplayKeyBoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayKeyBoBActionPerformed(evt);
            }
        });

        btnKeyAB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKeyAB.setText("Public Key");
        btnKeyAB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeyABActionPerformed(evt);
            }
        });

        btnEncyptKAB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEncyptKAB.setText("Encypt KAB");
        btnEncyptKAB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncyptKABActionPerformed(evt);
            }
        });

        btnEncOrDec.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEncOrDec.setText("Encypt/Decrypt");
        btnEncOrDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncOrDecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKeyAlice, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKeyBoB, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEncOrDec)
                            .addComponent(txtEncyptKAB, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtKeyKAB)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKeyAlice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDisplayKeyBoB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKeyAB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEncyptKAB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(186, 186, 186))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtKeyAlice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKeyAlice))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtKeyBoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDisplayKeyBoB))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtKeyKAB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKeyAB))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEncyptKAB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEncyptKAB))
                .addGap(18, 18, 18)
                .addComponent(btnEncOrDec)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    KeyAgreement aliceKeyAgree;
    PublicKey bobPubKey;
    SecretKey aliceDesKey;
    Cipher aliceCipher;
            
            
    private void txtKeyAliceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKeyAliceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKeyAliceActionPerformed

    private void btnKeyABActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeyABActionPerformed
        // TODO add your handling code here:
        try{
            FileInputStream fis = new FileInputStream("D:\\B.pub");
            byte[] bobPubKeyEnc = new byte[fis.available()];
            fis.read(bobPubKeyEnc);
            fis.close();
            
            KeyFactory aliceKeyFac = KeyFactory.getInstance("DH");
            X509EncodedKeySpec x509KeySpec = new X509EncodedKeySpec(bobPubKeyEnc);
            bobPubKey = aliceKeyFac.generatePublic (x509KeySpec);
            System.out.println("Execting PHASE1 of Key Agreement...");
            aliceKeyAgree.doPhase(bobPubKey, true);
            byte[] aliceShareSecret = aliceKeyAgree.generateSecret();
            
            System.out.println("Public Key: Secret (DEBUG ONLY):  " + CryptoUtil.toHexString(aliceShareSecret));
            txtKeyKAB.setText(CryptoUtil.toHexString(aliceShareSecret));
                    
        }
        catch (Exception ex)
        {
            
        }
    }//GEN-LAST:event_btnKeyABActionPerformed

    private void btnEncOrDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncOrDecActionPerformed
        // TODO add your handling code here:
        DESCS des = new DESCS();
        des.setVisible(true);
    }//GEN-LAST:event_btnEncOrDecActionPerformed

    private void btnKeyAliceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeyAliceActionPerformed
        // TODO add your handling code here:
        try{
            AlgorithmParameterGenerator paramGen = AlgorithmParameterGenerator.getInstance("DH");
            paramGen.init(512);
            AlgorithmParameters params = paramGen.generateParameters();
            
            DHParameterSpec dhSkipParamSpec = (DHParameterSpec) params.getParameterSpec(DHParameterSpec.class);
            
            System.out.println("Generating a DH KeyPair...");
            KeyPairGenerator aliceKpairGen = KeyPairGenerator.getInstance("DH");
            aliceKpairGen.initialize(dhSkipParamSpec);
            KeyPair aliceKpair = aliceKpairGen.generateKeyPair();
            
            System.out.println("Initializing the KeyAgreement Engine with DH private key");
            aliceKeyAgree = KeyAgreement.getInstance("DH");
            aliceKeyAgree.init(aliceKpair.getPrivate());
            
            byte[] alicePubKeyEnc = aliceKpair.getPublic().getEncoded();
            FileOutputStream fos = new FileOutputStream("D:\\A.pub");
            fos.write(alicePubKeyEnc);
            fos.close();
            txtKeyAlice.setText(alicePubKeyEnc.toString());
        } catch (Exception ex){}
    }//GEN-LAST:event_btnKeyAliceActionPerformed

    private void btnDisplayKeyBoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayKeyBoBActionPerformed
        // TODO add your handling code here:
        
        try{
            FileInputStream fis = new FileInputStream("D:\\B.pub");
            byte[] bkeyP=new byte[fis.available()];
            fis.read(bkeyP);
            fis.close();
            txtKeyBoB.setText(bkeyP.toString());
        } catch (Exception ex) {}
    }//GEN-LAST:event_btnDisplayKeyBoBActionPerformed

    private void btnEncyptKABActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncyptKABActionPerformed
        // TODO add your handling code here:
        // ma hoa chung bang thuat toan DES
        
        try{
            aliceKeyAgree.doPhase(bobPubKey,true);
            aliceDesKey = aliceKeyAgree.generateSecret("DES");
            txtEncyptKAB.setText(aliceDesKey.toString());
            BufferedWriter bw = null;
            String fileName="D:\\KeyA.txt";
                    bw=new
                BufferedWriter(new FileWriter(fileName));
                    bw.write(aliceDesKey.toString());
                    bw.close();
        }catch(Exception ex){}
    }//GEN-LAST:event_btnEncyptKABActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDisplayKeyBoB;
    private javax.swing.JButton btnEncOrDec;
    private javax.swing.JButton btnEncyptKAB;
    private javax.swing.JButton btnKeyAB;
    private javax.swing.JButton btnKeyAlice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtEncyptKAB;
    private javax.swing.JTextField txtKeyAlice;
    private javax.swing.JTextField txtKeyBoB;
    private javax.swing.JTextField txtKeyKAB;
    // End of variables declaration//GEN-END:variables
}
